name = "rsa_keys"
version = "1.1.0"

description = "A small library to help with rsa keys and message signing"
licences = ["Apache-2.0"]
repository = { type = "github", user = "jmrflora", repo = "rsa_keys" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
